### ISSUE TITLE
Provide option to use current date when generating docs

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/znai#302]
The date at the top of each page currently corresponds to the last modification date of the Markdown file.  I think for hosted pages (e.g. gh-pages), this might be confusing for users if each page has a different date.  Would be good to provide an option to generate docs with current date.

**Comment by MykolaGolubyev** [comment]
@jyeakel do you have any objections if we add a parameter to command line tool to force a different strategy for calculating "last update date"? 
Do you think it still makes sense for internal docs to have individual pages update date?

**Comment by jyeakel** [comment]
Honestly, it's hard to make sense of dates in Two Sigma so I don't expect they mean much to users today. I think because of the ways most users deploy (monorepo push, jenkins pipeline), most of the internal documentation all has the same date for each of its pages. The only ones I see that have different dates for different pages are ones that I know for a fact are where users manually run znai `--upload` from their terminal.

A parameter is definitely fine, but I also think just making all pages have the same date is okay as well.

**Comment by MykolaGolubyev** [comment]
If it doesn't add value currently I will change the default behavior then. Thanks.
